FROM python:3-alpine

WORKDIR /frontend

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY . .

# Set environment variables for Flask
ENV FLASK_APP=frontend.py
ENV FLASK_ENV=development

EXPOSE 5000

CMD ["flask", "run", "--host", "0.0.0.0", "--port", "5000"]
